version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - nginxcomnode-network
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules # volume anonimo (link simbolicos)
    entrypoint: sh -c "npm install && node index.js"
    tty: true
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginxcomnode-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - nginxcomnode-network

networks:
  nginxcomnode-network:
    driver: bridge