version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - nginxcomnode-network
    volumes:
      - ./node:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - nginxcomnode-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - nginxcomnode-network

networks:
  nginxcomnode-network:
    driver: bridge
